// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO00hcm_K_XqgqxAeL_EeqbU4WJfHIX2s',
    appId: '1:889483409620:web:e7c210593d729635a62341',
    messagingSenderId: '889483409620',
    projectId: 'doctor-bike-1323e',
    authDomain: 'doctor-bike-1323e.firebaseapp.com',
    storageBucket: 'doctor-bike-1323e.firebasestorage.app',
    measurementId: 'G-207FKGGN5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDge4XGPw6OVrvK_051-1ELHnU8EBIzah8',
    appId: '1:960923193223:android:22444bf8e9f751ad24cd22',
    messagingSenderId: '960923193223',
    projectId: 'drbike-7fa3a',
    storageBucket: 'drbike-7fa3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHTfwFtF-zzpa2Rs-Xs1likTgrMCfdGyU',
    appId: '1:960923193223:ios:9dd769b3304edfa924cd22',
    messagingSenderId: '960923193223',
    projectId: 'drbike-7fa3a',
    storageBucket: 'drbike-7fa3a.firebasestorage.app',
    iosBundleId: 'com.hazemAyad.doctorBike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp1_1BeNhkbtuaFyx4zu1jm9ilzpxzq3w',
    appId: '1:889483409620:ios:1ad1a52ccc27dd56a62341',
    messagingSenderId: '889483409620',
    projectId: 'doctor-bike-1323e',
    storageBucket: 'doctor-bike-1323e.firebasestorage.app',
    iosBundleId: 'com.example.doctorBike',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO00hcm_K_XqgqxAeL_EeqbU4WJfHIX2s',
    appId: '1:889483409620:web:04bf8ca4ebcb1285a62341',
    messagingSenderId: '889483409620',
    projectId: 'doctor-bike-1323e',
    authDomain: 'doctor-bike-1323e.firebaseapp.com',
    storageBucket: 'doctor-bike-1323e.firebasestorage.app',
    measurementId: 'G-S37JHZKN2B',
  );
}
